import type { DbShape } from "./types";

const t = (minsAgo: number) => Date.now() - minsAgo * 60 * 1000;
const h = (hoursAgo: number) => Date.now() - hoursAgo * 3600 * 1000;
const d = (daysAgo: number) => Date.now() - daysAgo * 86400 * 1000;

// Seed accounts use "plain:<password>" markers. On first successful login the
// auth route transparently upgrades them to real bcrypt hashes and persists.
//   admin@nevx.io  → admin123  (SUPER_ADMIN)
//   everyone else  → password123
const PW_USER = "plain:password123";
const PW_ADMIN = "plain:admin123";

export function buildSeed(): DbShape {
  return {
    seq: 10296,
    users: [
      {
        id: "u_admin",
        name: "NEVX Admin",
        email: "admin@nevx.io",
        passwordHash: PW_ADMIN,
        country: "United Arab Emirates",
        telegram: "nevx_support",
        avatarColor: "#0e2a5c",
        role: "SUPER_ADMIN",
        status: "ACTIVE",
        verified: true,
        rating: 5,
        ratingCount: 120,
        createdAt: d(300),
      },
      {
        id: "u_priya",
        name: "Priya Sharma",
        email: "priya@example.com",
        passwordHash: PW_USER,
        country: "India",
        telegram: "priya_s",
        avatarColor: "#0e7490",
        role: "USER",
        status: "ACTIVE",
        verified: true,
        rating: 4.8,
        ratingCount: 23,
        createdAt: d(180),
      },
      {
        id: "u_rahul",
        name: "Rahul Verma",
        email: "rahul@example.com",
        passwordHash: PW_USER,
        country: "India",
        avatarColor: "#7c3aed",
        role: "USER",
        status: "ACTIVE",
        verified: true,
        rating: 4.6,
        ratingCount: 11,
        createdAt: d(150),
      },
      {
        id: "u_sophia",
        name: "Sophia Carter",
        email: "sophia@example.com",
        passwordHash: PW_USER,
        country: "United States",
        telegram: "sophia_c",
        avatarColor: "#db2777",
        role: "USER",
        status: "ACTIVE",
        verified: true,
        rating: 4.9,
        ratingCount: 31,
        createdAt: d(200),
      },
      {
        id: "u_liam",
        name: "Liam Chen",
        email: "liam@example.com",
        passwordHash: PW_USER,
        country: "China",
        avatarColor: "#059669",
        role: "USER",
        status: "ACTIVE",
        verified: false,
        rating: 4.4,
        ratingCount: 8,
        createdAt: d(90),
      },
      {
        id: "u_anna",
        name: "Anna Müller",
        email: "anna@example.com",
        passwordHash: PW_USER,
        country: "Germany",
        telegram: "anna_m",
        avatarColor: "#ea580c",
        role: "USER",
        status: "ACTIVE",
        verified: true,
        rating: 4.7,
        ratingCount: 15,
        createdAt: d(120),
      },
      {
        id: "u_omar",
        name: "Omar Khan",
        email: "omar@example.com",
        passwordHash: PW_USER,
        country: "United Arab Emirates",
        avatarColor: "#4f46e5",
        role: "USER",
        status: "ACTIVE",
        verified: false,
        rating: 4.2,
        ratingCount: 5,
        createdAt: d(40),
      },
      {
        id: "u_diego",
        name: "Diego Santos",
        email: "diego@example.com",
        passwordHash: PW_USER,
        country: "Brazil",
        avatarColor: "#0891b2",
        role: "USER",
        status: "ACTIVE",
        verified: false,
        rating: 4.5,
        ratingCount: 9,
        createdAt: d(30),
      },
      {
        id: "u_mei",
        name: "Mei Wang",
        email: "mei@example.com",
        passwordHash: PW_USER,
        country: "Singapore",
        avatarColor: "#be185d",
        role: "USER",
        status: "ACTIVE",
        verified: true,
        rating: 5,
        ratingCount: 18,
        createdAt: d(60),
      },
    ],
    groups: [
      { id: "g_world", name: "WORLD", code: "world", country: "Global", active: true, order: 0 },
      { id: "g_india", name: "INDIA", code: "in", country: "India", active: true, order: 1 },
      { id: "g_usa", name: "USA", code: "us", country: "United States", active: true, order: 2 },
      { id: "g_china", name: "CHINA", code: "cn", country: "China", active: true, order: 3 },
      { id: "g_germany", name: "GERMANY", code: "de", country: "Germany", active: true, order: 4 },
      { id: "g_uae", name: "UAE", code: "ae", country: "United Arab Emirates", active: true, order: 5 },
    ],
    categories: [
      { id: "c_web", name: "Web Development", icon: "💻" },
      { id: "c_design", name: "Graphic Design", icon: "🎨" },
      { id: "c_marketing", name: "Marketing", icon: "📣" },
      { id: "c_writing", name: "Writing", icon: "✍️" },
      { id: "c_video", name: "Video & Editing", icon: "🎬" },
      { id: "c_tech", name: "Technology", icon: "🔌" },
      { id: "c_elec", name: "Electronics", icon: "📱" },
      { id: "c_home", name: "Home", icon: "🏠" },
      { id: "c_business", name: "Business", icon: "💼" },
      { id: "c_edu", name: "Education", icon: "🎓" },
      { id: "c_consult", name: "Consulting", icon: "🧠" },
      { id: "c_digital", name: "Digital Products", icon: "💿" },
      { id: "c_clothing", name: "Clothing", icon: "👕" },
      { id: "c_other", name: "Other", icon: "📦" },
    ],
    needs: [
      {
        id: "n1",
        userId: "u_sophia",
        groupId: "g_world",
        title: "I need a website developer",
        description:
          "I need a professional business website with booking system, mobile responsive, delivered with source files. Design references will be shared by NEVX admin.",
        category: "Web Development",
        subcategory: "Business site",
        budgetMin: 200,
        budgetMax: 400,
        budgetType: "range",
        country: "United States",
        deadline: "2 weeks",
        status: "ACTIVE",
        applicationCount: 7,
        createdAt: t(5),
      },
      {
        id: "n2",
        userId: "u_priya",
        groupId: "g_india",
        title: "I need a logo designer",
        description:
          "Minimal premium logo for a YouTube finance channel. Need 3 concepts + source files.",
        category: "Graphic Design",
        budgetMin: 50,
        budgetMax: 50,
        budgetType: "fixed",
        country: "India",
        status: "ACTIVE",
        applicationCount: 4,
        createdAt: t(40),
      },
      {
        id: "n3",
        userId: "u_omar",
        groupId: "g_world",
        title: "I need a used iPhone 15",
        description:
          "Looking for iPhone 15, 128GB, battery health above 88%, with bill. Budget negotiable through admin.",
        category: "Electronics",
        budgetMin: 500,
        budgetMax: 650,
        budgetType: "range",
        country: "United Arab Emirates",
        status: "ACTIVE",
        applicationCount: 3,
        createdAt: h(2),
      },
      {
        id: "n4",
        userId: "u_anna",
        groupId: "g_germany",
        title: "I need a thumbnail designer for YouTube",
        description:
          "Ongoing work — 8 thumbnails per month for a tech channel. Bold style, fast turnaround.",
        category: "Graphic Design",
        budgetMin: 10,
        budgetMax: 15,
        budgetType: "range",
        country: "Germany",
        status: "ACTIVE",
        applicationCount: 6,
        createdAt: h(5),
      },
      {
        id: "n5",
        userId: "u_liam",
        groupId: "g_china",
        title: "I need a Shopify store setup",
        description: "Small electronics store, 20 products, payment + shipping configured.",
        category: "Web Development",
        budgetType: "negotiable",
        country: "China",
        status: "ACTIVE",
        applicationCount: 2,
        createdAt: h(9),
      },
      {
        id: "n6",
        userId: "u_diego",
        groupId: "g_world",
        title: "I need a video editor for reels",
        description: "30 short reels per month, captions + trending cuts. Sample links available.",
        category: "Video & Editing",
        budgetMin: 150,
        budgetMax: 250,
        budgetType: "range",
        country: "Brazil",
        status: "ACTIVE",
        applicationCount: 5,
        createdAt: h(14),
      },
      {
        id: "n7",
        userId: "u_mei",
        groupId: "g_usa",
        title: "I need SEO for my SaaS landing page",
        description: "Technical audit + 10 pages optimized. English content, B2B SaaS niche.",
        category: "Marketing",
        budgetMin: 300,
        budgetMax: 300,
        budgetType: "fixed",
        country: "Singapore",
        status: "ACTIVE",
        applicationCount: 1,
        createdAt: d(1),
      },
      {
        id: "n8",
        userId: "u_rahul",
        groupId: "g_india",
        title: "I need a home tutor for Class 10 Maths",
        description: "Online classes, 4 days a week, CBSE syllabus. Evening slots preferred.",
        category: "Education",
        budgetMin: 80,
        budgetMax: 120,
        budgetType: "range",
        country: "India",
        status: "ACTIVE",
        applicationCount: 2,
        createdAt: d(2),
      },
    ],
    offers: [
      {
        id: "o1",
        userId: "u_rahul",
        groupId: "g_world",
        title: "I build professional business websites",
        description:
          "Modern, fast, SEO-ready business websites with WhatsApp integration and admin panel. 40+ sites delivered.",
        category: "Web Development",
        price: 199,
        priceType: "from",
        country: "India",
        deliveryTime: "5–7 days",
        status: "ACTIVE",
        createdAt: t(20),
      },
      {
        id: "o2",
        userId: "u_priya",
        groupId: "g_world",
        title: "YouTube thumbnails that get clicks",
        description: "Bold, high-CTR thumbnails. Unlimited revisions on first design.",
        category: "Graphic Design",
        price: 10,
        priceType: "fixed",
        country: "India",
        deliveryTime: "24 hours",
        status: "ACTIVE",
        createdAt: h(1),
      },
      {
        id: "o3",
        userId: "u_mei",
        groupId: "g_world",
        title: "iPhone 15 available — mint condition",
        description: "128GB Blue, 91% battery, full kit + bill. Escrow via NEVX admin only.",
        category: "Electronics",
        price: 620,
        priceType: "fixed",
        country: "Singapore",
        deliveryTime: "3–5 days",
        status: "ACTIVE",
        createdAt: h(3),
      },
      {
        id: "o4",
        userId: "u_diego",
        groupId: "g_usa",
        title: "Reels & TikTok editing pack",
        description: "Captions, hooks, sound sync. 10 reels pack with 48h delivery.",
        category: "Video & Editing",
        price: 99,
        priceType: "from",
        country: "Brazil",
        deliveryTime: "48 hours",
        status: "ACTIVE",
        createdAt: h(7),
      },
      {
        id: "o5",
        userId: "u_anna",
        groupId: "g_germany",
        title: "Brand identity + logo systems",
        description: "Logo, colors, typography and mini brand book for startups.",
        category: "Graphic Design",
        price: 149,
        priceType: "from",
        country: "Germany",
        deliveryTime: "1 week",
        status: "ACTIVE",
        createdAt: d(1),
      },
      {
        id: "o6",
        userId: "u_liam",
        groupId: "g_china",
        title: "Shopify setup in 3 days",
        description: "Theme, products, payments and shipping — launch-ready store.",
        category: "Web Development",
        price: 250,
        priceType: "fixed",
        country: "China",
        deliveryTime: "3 days",
        status: "ACTIVE",
        createdAt: d(2),
      },
    ],
    applications: [
      {
        id: "a1",
        needId: "n1",
        applicantId: "u_rahul",
        price: 350,
        deliveryTime: "7 days",
        message: "I can build this with Next.js + booking system. 40+ business sites delivered.",
        status: "PENDING",
        createdAt: t(30),
      },
      {
        id: "a2",
        needId: "n1",
        applicantId: "u_liam",
        price: 380,
        deliveryTime: "10 days",
        message: "Full-stack dev, can include admin panel and SEO setup.",
        status: "PENDING",
        createdAt: h(1),
      },
      {
        id: "a3",
        needId: "n3",
        applicantId: "u_mei",
        price: 620,
        deliveryTime: "4 days",
        message: "My iPhone 15 listing matches this exactly — bill and box included.",
        status: "APPROVED",
        createdAt: h(2),
      },
      {
        id: "a4",
        needId: "n2",
        applicantId: "u_anna",
        price: 60,
        deliveryTime: "3 days",
        message: "Brand designer — will share 3 premium concepts.",
        status: "PENDING",
        createdAt: h(3),
      },
      {
        id: "a5",
        needId: "n4",
        applicantId: "u_priya",
        price: 12,
        deliveryTime: "24 hours",
        message: "Thumbnail specialist, 200+ thumbnails for tech channels.",
        status: "PENDING",
        createdAt: h(4),
      },
      {
        id: "a6",
        needId: "n6",
        applicantId: "u_diego",
        price: 200,
        deliveryTime: "Monthly",
        message: "I edit 30 reels/month packs with captions and hooks.",
        status: "REJECTED",
        createdAt: h(10),
      },
    ],
    deals: [
      {
        id: "NVX-10291",
        needId: "n1",
        applicationId: "a1",
        buyerId: "u_sophia",
        sellerId: "u_rahul",
        title: "Business website development",
        agreedPrice: 350,
        commission: 35,
        finalAmount: 385,
        paymentStatus: "Pending",
        deliveryStatus: "Pending",
        status: "Negotiating",
        createdAt: h(20),
        updatedAt: h(2),
      },
      {
        id: "NVX-10292",
        needId: "n3",
        applicationId: "a3",
        buyerId: "u_omar",
        sellerId: "u_mei",
        title: "iPhone 15 purchase",
        agreedPrice: 620,
        commission: 31,
        finalAmount: 651,
        paymentStatus: "Received",
        deliveryStatus: "In Progress",
        status: "In Progress",
        createdAt: d(1),
        updatedAt: h(6),
      },
      {
        id: "NVX-10288",
        needId: "n8",
        applicationId: "a6",
        buyerId: "u_rahul",
        sellerId: "u_mei",
        title: "Maths tutoring — completed",
        agreedPrice: 100,
        commission: 10,
        finalAmount: 110,
        paymentStatus: "Received",
        deliveryStatus: "Delivered",
        status: "Completed",
        createdAt: d(20),
        updatedAt: d(5),
      },
    ],
    messages: [
      {
        id: "m1",
        dealId: "NVX-10291",
        side: "buyer",
        sender: "admin",
        text: "Hi Sophia! Rahul can deliver in 7 days for $350. Shall I lock this price?",
        createdAt: h(18),
      },
      {
        id: "m2",
        dealId: "NVX-10291",
        side: "buyer",
        sender: "user",
        text: "Yes please — can he also include basic SEO?",
        createdAt: h(12),
      },
      {
        id: "m3",
        dealId: "NVX-10291",
        side: "seller",
        sender: "admin",
        text: "Hi Rahul! Buyer accepted $350. Please confirm SEO inclusion.",
        createdAt: h(11),
      },
      {
        id: "m4",
        dealId: "NVX-10292",
        side: "buyer",
        sender: "admin",
        text: "Payment received, Omar. Seller is shipping the device with tracking.",
        createdAt: h(6),
      },
      {
        id: "m5",
        dealId: "NVX-10292",
        side: "seller",
        sender: "user",
        text: "Shipped today, tracking shared with admin.",
        createdAt: h(5),
      },
    ],
    notifications: [
      {
        id: "nt1",
        userId: "u_sophia",
        icon: "🔔",
        text: "Deal NVX-10291 is now active.",
        read: false,
        link: "/app/deals/NVX-10291",
        createdAt: h(18),
      },
      {
        id: "nt2",
        userId: "u_rahul",
        icon: "🔔",
        text: "NEVX Admin has sent you a message.",
        read: false,
        link: "/app/deals/NVX-10291",
        createdAt: h(11),
      },
      {
        id: "nt3",
        userId: "u_mei",
        icon: "✅",
        text: "Your application was selected.",
        read: false,
        link: "/app/applications",
        createdAt: d(1),
      },
    ],
    reports: [
      {
        id: "r1",
        reporterId: "u_sophia",
        targetType: "offer",
        targetId: "o3",
        reason: "Fake listing",
        details: "Please verify device bill.",
        status: "OPEN",
        createdAt: d(1),
      },
    ],
  };
}
